### ISSUE TITLE
Update 2.1 TCK to allow certification using Java 21

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/batch-tck#66]
Consider updating https://github.com/eclipse-ee4j/batch-tck/blob/master/pom.xml#L476 to also allow Java 21.

**Comment by chengfang** [comment]
@scottkurz It seems too restrictive for the batch-tck to enforce the java version to under 18. What's your take? 

Process wise, is it possible to release a maintenance version of tck within Jakarta EE?

**Comment by scottkurz** [comment]
> @scottkurz It seems too restrictive for the batch-tck to enforce the java version to under 18. What's your take?

If I remember correctly, my thought was simply to force us to have this discussion.  Especially because of the signature test aspect of this TCK, this project needs some extra attention when considering new Java levels to ensure the right validation is included.
 
> Process wise, is it possible to release a maintenance version of tck within Jakarta EE?

Good question. I haven't looked at how this might fit in with the various processes and with what other specs are doing.

**Comment by scottmarlow** [comment]
On Fri, Sep 29, 2023, 1:30 PM Scott Kurz ***@***.***> wrote:

> @scottkurz <https://github.com/scottkurz> It seems too restrictive for
> the batch-tck to enforce the java version to under 18. What's your take?
>
> If I remember correctly, my thought was simply to force us to have this
> discussion. Especially because of the signature test aspect of this TCK,
> this project needs some extra attention when considering new Java levels to
> ensure the right validation is included.
>
> Process wise, is it possible to release a maintenance version of tck
> within Jakarta EE?
>
>
I think yes.

> Good question. I haven't looked at how this might fit in with the various
> processes and with what other specs are doing.
>
Fyi, I also opened https://github.com/jakartaee/platform-tck/issues/1192
for (EE 10) platform TCK signature test failures that I don't think impacts
the Batch TCK but still mentioning to share some longer term suggestions to
improve signature testing mentioned in the linked issue.

Scott

**Comment by liweinan** [comment]
I have tested JBeret with `batch-tck` and the tests passed except the `sigtest` needs to be updated for Java 21.

**Comment by scottmarlow** [comment]
@liweinan thanks for mentioning ^ as I think it would be good to address that.

**Comment by liweinan** [comment]
This PR demonstrates that both the SE and the deployment TCK tests can be passed under JDK 21 and the latest version of WildFly: https://github.com/jberet/jberet-tck-runner/pull/8

**Comment by jamezp** [comment]
FWIW the sigtest-maven-plugin should like migrate to [`jakarta.tck:sigtest-maven-plugin:2.2`](https://github.com/eclipse-ee4j/jakartaee-tck-tools/releases/tag/sigtest-2.2) as there is better support for running in different JVM's.

I don't see where in the project these files are created.

**Comment by liweinan** [comment]
btw this is how it's done in REST https://github.com/jakartaee/rest/blob/5676ac815ad32d210b068400924aeff24063221f/jaxrs-tck/pom.xml#L173-L206

**Comment by scottmarlow** [comment]
@scottkurz could you please add the `challenge` label to this issue as I think this is a TCK challenge and should either be accepted or rejected soon after.  

CC @edburns

**Comment by edburns** [comment]
Thanks for the heads up.

**Comment by scottkurz** [comment]
> @scottkurz could you please add the challenge label to this issue as I think this is a TCK challenge and should either be accepted or rejected soon after.

@scottmarlow could you please help me understand why this would be considered a explain the process Would this be a challenge?  The 2.1 TCK was originally released with the goal of supporting Java 11 and 17, not 21.  

This feels like we're asking for a new release of the TCK, more like a 2.2.....or I don't know, maybe we call it something like 2.1.5 to indicate it's more substantive than a 2.1.2 would indicate.

Is the idea that a challenge takes us through an expedited review process?

**Comment by scottkurz** [comment]
Let me list the tasks as:  

- [ ] Update parent POM? (maybe)
- [ ] Broaden Maven enforcer checks to allow sigtest & runtime tests to include Java 21
- [ ] Switch to jakarta.test:sigtest-maven-plugin:2.2
- [ ] Update doc re: plugin change
- [ ] Generate Java 21 signature files
- [ ] Add Java 21 sigtest runner
- [ ] Update doc re: Java 21 signature tests
- [ ] Update doc re: support for Java 21 runtime tests
- [ ] Update doc re: overall support for Java 21

That list assumes the build and release (incl. handling the TCK update process) will be handled elsewhere.

**Comment by scottmarlow** [comment]
> > @scottkurz could you please add the challenge label to this issue as I think this is a TCK challenge and should either be accepted or rejected soon after.
> 
> @scottmarlow could you please help me understand why this would be considered a explain the process Would this be a challenge? The 2.1 TCK was originally released with the goal of supporting Java 11 and 17, not 21.

Yes but now we are delivering Jakarta EE 11 which supports Java 17 + 21 and is supposed to work with Batch 2.1.
 
> 
> This feels like we're asking for a new release of the TCK, more like a 2.2.....or I don't know, maybe we call it something like 2.1.5 to indicate it's more substantive than a 2.1.2 would indicate.
> 
> Is the idea that a challenge takes us through an expedited review process?

The Specification team will either accept or reject the promotion of the TCK service release but what do you have in mind for the Batch TCK service request review process?  

Do we need to make Batch SPEC API (or Batch Spec) changes to support Java 21?  If no, then I think a Batch TCK service release (with Java 21 support) for 2.1 could be considered.

https://github.com/jakartaee/platform-tck/issues/1192 is a Platform TCK challenge issue that was accepted to release a new Jakarta EE 10 Platform TCK that can pass the signature tests on Java 21 in addition to Java 11/17.  Other specifications have used TCK challenges for handling that kind of change.

**Comment by jamezp** [comment]
Just an FYI in the `jakarta.tck:sigtest-maven-plugin:2.2` you only need a generated signature file for the lowest JDK level, e.g. 11 in this case. When you check the validation, assuming the maven plugin here with the `check` goal, you simply need to add `<release>11</release>` and it should pass on all Java versions.

**Comment by scottkurz** [comment]
> Just an FYI in the `jakarta.tck:sigtest-maven-plugin:2.2` you only need a generated signature file for the lowest JDK level, e.g. 11 in this case. When you check the validation, assuming the maven plugin here with the `check` goal, you simply need to add `<release>11</release>` and it should pass on all Java versions.

Thank you.  I reworked https://github.com/jakartaee/batch-tck/issues/45 to refocus on this idea and linked your comment here.
