### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:transform ... a base directory of a ValidationSet or TransformationSet, does not exist

### ISSUE THREAD

**Issue by liweinan** [jakartaee/batch-tck#77]
While I'm trying to build the main branch locally with the following command:

```bash
➤ mvn clean install -DskipTests
```

I met the following build failure:

```
[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:transform (default) on project com.ibm.jbatch.tck.exec: The directory /Users/weli/works/batch-tck/com.ibm.jbatch.tck.exec/target/failsafe-reports, which is a base directory of a ValidationSet or TransformationSet, does not exist. -> [Help 1]
```

Here is the screenshot:

![image](https://github.com/jakartaee/batch-tck/assets/201907/938c010e-cb41-422a-a5e3-2cafc0e8e535)

The Java version I used is:

```bash
➤ java -version                                                                                                                                                                  15:56:02
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)
```

**Comment by liweinan** [comment]
@scottkurz Could you please help to check it when you have time? Thanks!

**Comment by liweinan** [comment]
Here is the build failure from Github CI for reference: https://github.com/jberet/jberet-tck-runner/actions/runs/8519549775/job/23333826132#step:4:7035

**Comment by scottkurz** [comment]
OK, I recreated the issue.    

The failing goal is new reporting I added to collect the different integration test executions into a single report.   

Let me see if I can see how to fix this.   It could also just be reverted if needed.

**Comment by liweinan** [comment]
@scottkurz Thanks for checking!

**Comment by scottkurz** [comment]
OK, I looked into this more.

The problem could be avoided by running:
> mvn clean install -DskipTests -Dxml.skip -Decho.skip


We could imagine going a bit further and trying to skip this whenever tests aren't runned.

E.g. I had the though to try: 

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <configuration>
                    <skip>${skipTests}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.ekryd.echo-maven-plugin</groupId>
                <artifactId>echo-maven-plugin</artifactId>
                <configuration>
                    <skip>${skipTests}</skip>
                </configuration>
            </plugin>
```

though like the doc says https://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html#skipTests, this parameter isn't even recommended because we're using 'failsafe' (IT) to run these tests, and it's really more for 'surefire' (UT).  

I could still see making the case that it'd be better to include the above.   What do you think?

**Comment by liweinan** [comment]
@scottkurz I have verified the build can pass with the above configuration. Thanks for checking this! 

And +1 to the solution :D
